services:
  redis:
    image: redis/redis-stack-server:latest
    volumes:
      - ./redis:/data
    ports:
      - "6379:6379"

  api:
    build: api
    environment:
      - EXPRESS_PORT=80
      - EXPRESS_BASE_URL=/
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - redis

  # I found running embedders in a container to be too slow but your
  # mileage may vary. Uncomment below if you want to try it out.

  # embedder:
  #   build: embedder
  #   deploy:
  #     replicas: 1
  #     resources:
  #       limits:
  #         memory: 12G
  #   environment:
  #     - REDIS_HOST=redis
  #     - REDIS_PORT=6379
  #   depends_on:
  #     - redis

  web:
    build: web
    depends_on:
      - api

  gateway:
    build: gateway
    ports:
      - "8080:80"
    depends_on:
      - api
      - web
