services:
  redis:
    image: redis/redis-stack-server:latest
    volumes:
      - ./redis:/data
    ports:
      - "6379:6379"

  api:
    build: api
    ports:
      - "3000:80"
    environment:
      - EXPRESS_PORT=80
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - redis

  embedder:
    build: embedder
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - redis

  frontend:
    build: web
    ports:
      - "8080:80"
    depends_on:
      - api
