services:
  redis:
    image: redis/redis-stack-server:latest
    volumes:
      - ./redis:/data
    ports:
      - "6379:6379"

  api:
    build: api
    environment:
      - EXPRESS_PORT=80
      - EXPRESS_BASE_URL=/
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - redis

  embedder:
    build: embedder
    deploy:
      replicas: 3
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - redis

  web:
    build: web
    environment:
      - VITE_API_BASE_URL=/api
    depends_on:
      - api

  gateway:
    build: gateway
    ports:
      - "8080:80"
    depends_on:
      - api
      - web
